### ISSUE TITLE
black screen ingame

### ISSUE THREAD

**Issue by WilliamFoxx** [themrdemonized/STALKER-Anomaly-modded-exes#11]
After i installed this, when i load into map i have a black screen. I see hud, i hear sound, i can do anything but black screen. Anomaly 1.5.1

**Comment by themrdemonized** [comment]
Read the installation description

**Comment by victorstanciu** [comment]
Hey @WilliamFoxx, did you find a fix for this? I overwrote the executables in the `bin` folder and reset the shader cache, but I have the same issue you did. HUD works, movement and shooting works, sound works, I can even open the inventory, but everything else is black. I don't know what description @themrdemonized means, because I did everything in the [README.md](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/tree/97944f2ddc28400e4ec83e0a8c1f3ff0f52d82d0#readme) for this version.
